Fix invalid name of k8s secret and change dump filename
benjamin-maynard/kubernetes-cloud-mysql-backup pull request #7
Opened 2019-08-14 14:01 UTC by kuzm1ch

1) Seems Use upper case is not allowed for kubernetes secret name.
The Secret "AWS_SECRET_ACCESS_KEY" is invalid: metadata.name: Invalid value: "AWS_SECRET_ACCESS_KEY": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
2) dump filename should consist  timespamp
* to do not overwrite old one 
* e.g. gitlab backup which is created by their native backup command 1565092253_2019_08_06_11.11.0-ee_gitlab_backup.tar

2019-08-15 12:55 UTC, benjamin-maynard requested changes
Hey @kuzm1ch,

Thanks a lot for the Pull Request, and good catch on the secrets naming. I deploy using Terraform so didn't catch that one.

Happy to add a date to the backup file name, however as per the README.md I intentionally left the date out of the backup file.

>kubernetes-s3-mysql-backup performs a backup to the same path, with the same filename each time it runs. It therefore assumes that you have Versioning enabled on your S3 Bucket. A typical setup would involve S3 Versioning, with a Lifecycle Policy.

I've seen a few other Forks add the date option, so happy to include it. However would prefer it was an option configurable via an environment variable, whereby the default remains as it is now. It will also minimise impact to those using the `:latest` tag.

Is this something you're able to update? If not, I am happy to merge it into another branch and tweak.

2019-08-16 06:20 UTC, benjamin-maynard commented
@kuzm1ch - to add to this, think time should also be added to cater for those taking backup more than once per day. So that if they do not have versioning enabled they are not overwriting their own backups.

2019-08-16 09:34 UTC, kuzm1ch commented
Yes, I agree that it will be good to provide customization of timestamp in backup based on env variable, but I would rather do it as the new pull request in the next week. 
@benjamin-maynard 
Some idea on implementation:
1) Provide behavior to choose what timestamp backup should include 
              - name: BACKUP_TIMESTAMP
                value: "<none/day/hour/minute/seconds>"
2) Or make it fully configurable:
                value: " _%Y_%m_%d"
                value: ""
the second is more preaty for me

2019-08-18 14:55 UTC, benjamin-maynard commented
Hey @kuzm1ch 

I agree, option 2 seems more elegant, and configurable. Let me know where I can help, happy for you to submit it as a new PR but if you want me to do any of the heavy lifting just let me know.

Thanks again for your contributions.

2019-08-27 16:42 UTC, kuzm1ch commented
@benjamin-maynard Hi, I have force push ))  my last commit. Please check.

2019-08-28 08:25 UTC, benjamin-maynard commented
@kuzm1ch This is great - tested it this morning and happy to merge!

2019-08-28 08:25 UTC, merged